# Pipeline to run basic code quality tests as part of pull requests to the main branch.
parameters:
  - name: workingDirectory
    displayName: Working Directory for sample
    type: string
    default: samples/image-classification-tensorflow

resources:
  containers:
  - container: mlops

trigger: none

pr:
  branches:
    include:
    - main
  paths:
    include:
    - samples/image-classification-tensorflow
    exclude:
    - samples/image-classification-tensorflow/.env.example
    - README.md
    - LICENSE

pool:
  vmImage: 'ubuntu-latest'

container: mlops

variables:
- template: variables-template.yml
#- group: devopsforai-aml-vg

steps:
- template: code-quality-template.yml
  parameters:
    workingDirectory: ${{ parameters.workingDirectory }}
